openapi: "3.1.0"
info:
  title: API Users
  version: "1.0"
paths:
  /api/users/:
    get:
      summary: Obtienes todos los usuarios
      tags:
        - "Users"
      responses:
        "200":
          description: Todos los usuario fueron obtenidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "400":
          description: Bad request
        "500":
          description: Internal server error
  /api/users/{uid}:
    get:
      summary: Obtienes un solo usuario
      tags:
        - Users
      parameters:
        - name: uid
          in: path
          required: true
          description: id del usuario que buscas
          schema:
            type: string
      responses:
        "200":
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    put:
      summary: Actualiza un usuario
      tags:
      - Users
      parameters:
      - name: uid
        in: path
        required: true
        description: id del usuario
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/updateUser"
              
components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          description: Id de mongo
        first_name:
          type: string
          description: Nombre del usuario
        last_name:
          type: string
          description: Apellido del usuario
        email:
          type: string
          description: Correo del usuario
        password:
          type: string
          description: Contraseña del usuario
      example:
        _id: ObjectId("87whc8hfte78hcs9dhg8")
        first_name: Francisco
        last_name: Reinoso
        email: Fran@gmail.com
        password: sdjcfhse98fcjrfha78chef78h4a87cfhw8a7h87
  requestBodies:      
    updateUser:
      description: Body con la info del usuario a actualizar
      properties:
        first_name:
          type: string
          description: Nombre del usuario
        last_name:
          type: string
          description: Apellido del usuario
        email:
          type: string
          description: Correo del usuario
        password:
          type: string
          description: Contraseña del usuario
      example:
        first_name: Aylen
        last_name: Reinoso
        email: Aylen@gmail.com
        password: 1234567